name = "worker"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-05"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
